name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    # - run: npm install
    # - run: npm run build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: digitalocean/action-doctl@v2
      with:
        token: ${{secrets.DIGITAL_OCEAN_SECRET}}
    - name: Save DigitalOcean kubeconfig
      run: doctl compute ssh ubuntu-s-1vcpu-1gb-blr1-01
    - run: mkdir /home/helloo
    # - name: Executing remote  command
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.HOST }}
    #     USERNAME: ${{ secrets.USERNAME }}
    #     PORT: ${{ secrets.PORT }}
    #     KEY: ${{ secrets.SSH_KEY }}
    #     script: mkdir /home/hello_Worldc
    # - uses: actions/checkout@v1
    # - name: Copy file via scp
    #   uses: appleboy/scp-action@master
    #   env:
    #     HOST: ${{ secrets.HOST }}
    #     USERNAME: ${{ secrets.USERNAME }}
    #     PORT: ${{ secrets.PORT }}
    #     KEY: ${{ secrets.DIGITAL_OCEAN_SECRET }}
    #   with:
    #     source: "build"
    #     target: "/opt/app"
    # - uses: actions/checkout@v2
    # - uses: digitalocean/action-doctl@v2
    #   with:
    #     token: ${{secrets.DIGITAL_OCEAN_SECRET}}
    # - run: cd /home/
    # - run: mkdir hello
    # - run: git pull
    # - run: pm2 stop all
    # - run: pm2 serve build 3000
